# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FPT Banking' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
    pod 'SwiftyJSON'
    pod 'Alamofire', '~> 4.2'
    pod 'Toast-Swift'
    pod 'MBProgressHUD'
    pod 'SwiftyJSON'
  # Pods for FPT Banking
	
  target 'FPT BankingTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FPT BankingUITests' do
    # Pods for testing
  end

end
